  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  resources:
  - ./manifests/

  images:
    - name: PROJECT/IMAGE_FE
      newName: europe-north1-docker.pkg.dev/my-project/my-repository/todo-app

    - name: PROJECT/IMAGE_BE
      newName: europe-north1-docker.pkg.dev/my-project/my-repository/todo-app-back

    - name: PROJECT/IMAGE_BD
      newName: europe-north1-docker.pkg.dev/my-project/my-repository/broadcaster
