apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app-backend
  ports:
    - port: 5555
      protocol: TCP
      targetPort: 5555