name: Delete Environment on Branch Deletion

on: delete

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH_REF: "${{ github.event.ref }}"

jobs:
  delete-namespace:
    runs-on: ubuntu-latest
    name: Delete Namespace

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info
      
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Delete
        run: |-
          BRANCH_NAME="${BRANCH_REF#refs/heads/}"

          NAMESPACE=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')

          if [[ "$NAMESPACE" == "master" ]]; then
            NAMESPACE="project"
          fi

          echo "Deleting namespace: $NAMESPACE for branch: $BRANCH_NAME"

          kubectl delete namespace "$NAMESPACE" --ignore-not-found