name: Delete Environment on Branch Deletion

on: delete

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  IMAGE_FE: todo-app
  IMAGE_BE: todo-app-back
  SERVICE_FE: todo-app-depl
  SERVICE_BE: todo-app-backend-depl
  BRANCH: ${{ github.ref_name }}


jobs:
  delete-namespace:
    runs-on: ubuntu-latest
    name: Delete Namespace

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info
      
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Delete
        run: |-
          NAMESPACE=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          if [[ "$NAMESPACE" == "master" ]]; then
            NAMESPACE="project"
          fi
          kubectl delete namespace $NAMESPACE || true
